site_name: 5th Edition SRD

copyright: Rules provided by Wizards of the Coast under the <a href="/license">OGL 1.0a</a>.

theme:
  
  language: ru 
    
  font: Roboto
  
  features:
    - navigation.instant
    - navigation.top
    - toc.integrate
    - navigation.tabs
    - navigation.expand
  
plugins:
  - search:
      lang:
        - en
        - ru
        
markdown_extensions:
  - attr_list
  - admonition
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  
extra:
  social:
    - icon: fontawesome/brands/vk
      link: https://vk.com/cyborgsandmages
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Cyborgs-and-Mages-101450734568540    
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyborgsandmages
    - icon: fontawesome/brands/telegram
      link: https://t.me/cyborgs_and_mages
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xRCsKBQ
    - icon: fontawesome/brands/wordpress
      link: https://cyborgsandmages.wordpress.com

nav:
    - О ресурсе: 'index.md'
    - 'Приключения':
        - Между Приключениями: 'adventuring/between_adventures.md'
        - Перемещение: 'adventuring/movement.md'
        - Планы существования: 'adventuring/planes_of_existence.md'
        - Отдых: 'adventuring/resting.md'
        - Окружающая среда: 'adventuring/the_environmen.md'
        - Время: 'adventuring/time.md'
    - 'Снаряжение': 
            - Снаряжение: 'adventuring/equipment/adventuring_gear.md'
            - Доспехи: 'adventuring/equipment/armor.md'
            - Монеты: 'adventuring/equipment/coins.md'
            - Наборы снаряжения: 'adventuring/equipment/equipment_packs.md'
            - Верховые животные и транспортные средства: 'adventuring/equipment/mounts_and_vehicles.md'
            - Продажа Сокровищ: 'adventuring/equipment/selling_treasure.md'
            - Инструменты: 'adventuring/equipment/tools.md'
            - Товары: 'adventuring/equipment/trade_goods.md'
            - Оружие: 'adventuring/equipment/weapons.md'
    - 'Персонаж':
        - 'Основы':
            - Мировоззрение: 'character/alignment.md'
            - Предыстории: 'character/backgrounds.md'
            - Фэнтезийно-исторические пантеоны: 'character/fantasy-historical_pantheons.md'
            - Языки: 'character/languages.md'
        - 'Классы':
            - Варвар: 'character/classes/barbarian.md'
            - Бард: 'character/classes/bard.md'
            - Клерик: 'character/classes/cleric.md'
            - Друид: 'character/classes/druid.md'
            - Воин: 'character/classes/fighter.md'
            - Монах: 'character/classes/monk.md'
            - Паладин: 'character/classes/paladin.md'
            - Следопыт: 'character/classes/ranger.md'
            - Плут: 'character/classes/rogue.md'
            - Чародей: 'character/classes/sorcerer.md'
            - Колдун: 'character/classes/warlock.md'
            - Волшебник: 'character/classes/wizard.md'
        - 'Расы':
            - О расах: 'character/races/index.md'
            - Драконорожденный: 'character/races/dragonborn.md'
            - Дварф: 'character/races/dwarf.md'
            - Эльф: 'character/races/elf.md'
            - Гном: 'character/races/gnome.md'
            - Полуэльф: 'character/races/half-elf.md'
            - Полуорк: 'character/races/half-orc.md'
            - Халфлинг: 'character/races/halfling.md'
            - Человек: 'character/races/human.md'
            - Тифлинг: 'character/races/tiefling.md'
    - 'Сражение':
        - Действия в бою: 'combat/actions_in_combat.md'
        - Укрытие: 'combat/cover.md'
        - Урон и лечение: 'combat/damage_and_healing.md'
        - Совершение атаки: 'combat/making_an_attack.md'
        - Сражение верхом: 'combat/mounted_combat.md'
        - Перемещения и позиция: 'combat/movement_and_position.md'
        - Порядок Сражения: 'combat/order_of_combat.md'
        - Сражение под водой: 'combat/underwater_combat.md'
    - 'Правила для Игрока':
        - Преимущество и помеха: 'rules/advantage_and_disadvantage.md'
        - Состояния: 'rules/conditions.md'
        - Расходы: 'rules/expenses.md'
        - Черты: 'rules/feats.md'
        - Вдохновение: 'rules/inspiration.md'
        - Повышение уровня: 'rules/leveling_up.md'
        - Мультикласс: 'rules/multiclassing.md'
        - Бонус владения: 'rules/proficiency_bonus.md'
        - 'Характеристики':
            - Проверка Характеристик: 'rules/abilities/ability_checks.md'
            - Использование характеристик: 'rules/abilities/ability_scores.md'
            - Спасброски: 'rules/abilities/saving_throws.md'
            - Харизма: 'rules/abilities/charisma.md'
            - Телосложение: 'rules/abilities/constitution.md'
            - Ловкость: 'rules/abilities/dexterity.md'
            - Интеллект: 'rules/abilities/intelligence.md'
            - Сила: 'rules/abilities/strength.md'
            - Мудрость: 'rules/abilities/wisdom.md'
    - 'Правила для Мастера':
        - Болезни: 'gamemaster_rules/diseases.md'
        - Легендарные существа: 'gamemaster_rules/legendary_creatures.md'
        - Безумие: 'gamemaster_rules/madness.md'
        - Волшебные предметы: 'gamemaster_rules/magic_items.md'
        - Чудовища: 'gamemaster_rules/monsters.md'
        - Неигровые Персонажи : 'gamemaster_rules/nonplayer_characters.md'
        - Объекты: 'gamemaster_rules/objects.md'
        - Яды: 'gamemaster_rules/poisons.md'
        - Разумные магические предметы: 'gamemaster_rules/sentient_magical_items.md'
 
            
use_directory_urls: false
